#!/usr/bin/env python3
"""Validate the Jetson Nano DeepStream runtime configuration without starting the pipeline."""

import shutil
import subprocess
import sys
from pathlib import Path
from typing import List, Tuple

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from core.deepstream_config import (  # noqa: E402
    _config_lines,
    _detect_onnx_postprocess_ops,
    active_camera_ids,
    deepstream_config,
    load_labels,
    preflight_rtsp_sources,
    redact_uri,
    rtsp_source_uris,
    resolve_project_path,
    validate_rtsp_sources,
)


def check_file(label: str, path_value: str, required: bool = True) -> Tuple[bool, str]:
    path = Path(resolve_project_path(path_value))
    if path.exists():
        return True, f"OK {label}: {path}"
    prefix = "FAIL" if required else "WARN"
    return not required, f"{prefix} {label} not found: {path}"


def check_gst_element(name: str) -> Tuple[bool, str]:
    gst_inspect = shutil.which("gst-inspect-1.0")
    if gst_inspect is None:
        return True, "WARN gst-inspect-1.0 not found; skipping GStreamer plugin checks"
    try:
        result = subprocess.run(
            [gst_inspect, name],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=3,
            check=False,
        )
    except subprocess.TimeoutExpired:
        return True, f"WARN gst-inspect-1.0 timed out for {name}; check manually on Nano"
    if result.returncode == 0:
        return True, f"OK GStreamer element: {name}"
    return False, f"FAIL missing GStreamer element: {name}"


def main() -> int:
    ds = deepstream_config()
    camera_ids = active_camera_ids()
    checks: List[Tuple[bool, str]] = []

    try:
        validate_rtsp_sources(ds, camera_ids)
        sources = ", ".join(
            f"{cam_id}={redact_uri(uri)}" for cam_id, uri in rtsp_source_uris(ds, camera_ids)
        )
        checks.append((True, f"OK RTSP URI syntax: {sources}"))
    except Exception as exc:
        checks.append((False, f"FAIL RTSP URI syntax: {exc}"))

    if bool(ds.get("rtsp_preflight", True)):
        try:
            preflight_rtsp_sources(ds, camera_ids)
            checks.append((True, "OK RTSP preflight: sources answered RTSP"))
        except Exception as exc:
            checks.append((False, f"FAIL RTSP preflight: {exc}"))

    checks.append(check_file("ONNX model", str(ds.get("onnx_model_path") or "")))
    checks.append(check_file("labels file", str(ds.get("labels_path") or "")))
    checks.append(check_file("YOLO parser .so", str(ds.get("custom_parser_path") or "")))

    engine_path = Path(resolve_project_path(str(ds.get("engine_path") or "")))
    if engine_path.exists():
        checks.append((True, f"OK TensorRT engine exists: {engine_path}"))
    else:
        checks.append((True, f"OK TensorRT engine will be generated by nvinfer: {engine_path}"))

    try:
        labels = load_labels(str(ds.get("labels_path") or ""))
        expected = int(ds.get("num_detected_classes", 0))
        if len(labels) == expected:
            checks.append((True, f"OK labels count matches num_detected_classes: {expected}"))
        else:
            checks.append(
                (
                    False,
                    f"FAIL labels count {len(labels)} does not match num_detected_classes {expected}",
                )
            )
    except Exception as exc:
        checks.append((False, f"FAIL could not load labels: {exc}"))

    onnx_path = Path(resolve_project_path(str(ds.get("onnx_model_path") or "")))
    if onnx_path.exists():
        postprocess_ops = _detect_onnx_postprocess_ops(onnx_path)
        if postprocess_ops:
            checks.append(
                (
                    False,
                    "FAIL ONNX contains DeepStream-YOLO-incompatible postprocess ops: "
                    + ", ".join(postprocess_ops),
                )
            )
        else:
            checks.append((True, "OK ONNX postprocess scan: raw detector graph"))

    for element in ("rtspsrc", "nvv4l2decoder", "nvstreammux", "nvinfer", "fakesink"):
        checks.append(check_gst_element(element))
    if str(ds.get("sink_type", "fakesink")).lower() == "appsink":
        for element in ("nvvideoconvert", "nvdsosd", "appsink"):
            checks.append(check_gst_element(element))

    print("Generated nvinfer config preview:")
    print("\n".join(_config_lines(ds)))
    print("\nValidation:")
    ok = True
    gst_inspect_missing_reported = False
    for passed, message in checks:
        if message.startswith("WARN gst-inspect"):
            if gst_inspect_missing_reported:
                continue
            gst_inspect_missing_reported = True
        print(f"- {message}")
        ok = ok and passed

    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
